# Generated by Django 6.0.3 on 2026-04-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_userprofile_first_name_userprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('admin', 'admin'), ('client', 'client')], default='admin', max_length=10),
        ),
    ]
